### ISSUE TITLE
Unexpected result of merging cells across tbody/thead sections

### ISSUE THREAD

**Issue by zwz** [massifrg/prosemirror-tables-sections#2]
I think this operation should not be allowed at all.

**Comment by massifrg** [comment]
Hi zwz,
indeed it's not allowed; are you testing the latest version?
Because at some point I added a specific test for that.

In my demo the "Merge cells" doesn't even appear in the menu.

See [this line](https://github.com/massifrg/prosemirror-tables-sections/blob/e43266896ea2b8b6f176039fe243c8079d04f2e1/src/commands.ts#L677). It calls a function to test whether selection is over only one section.

Thanks for testing, let me know if the latest version works fine.

**Comment by zwz** [comment]
Yes, my bad.
It is solved in the latest version.
